title: openSUSE Kubic - Retired
title_short: Kubic - Retired
email: opensuse-factory@opensuse.org
description: Retired Kubernetes distribution & container-related technologies formerly built by the openSUSE community
copyright: '© 2017–2022 openSUSE contributors'
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
paginate: 10
paginate_path: "/blog/page:num/"
breadcrumb_icon: <img src="/assets/images/symbolic.svg" class="mr-1" style="height:1em; vertical-align:middle;">

enable_feed: true

navbar_links:
  -
    link: https://registry.opensuse.org/
    text: Registry
  -
    link: https://en.opensuse.org/Portal:Container
    text: Container Documentation
  -
    link: /blog
    text: Blog
  -
    icon: <svg class="bi bi-bell" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z"/><path fill-rule="evenodd" d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/></svg>
    link: /feed.xml
    text: RSS Feed

footer_links:
  -
    text: Source Code
    link: https://github.com/kubic-project/kubic-o-o
  -
    text: License
    link: https://github.com/kubic-project/kubic-o-o/blob/master/LICENSE

permalink: /blog/:year-:month-:day-:title/

theme: jekyll-theme-opensuse

messages:
  categories: 'Categories'
  tags: 'Tags'
  months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
  share_this_post: Share this post

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: cattag-archive
    category: cattag-archive

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

